# Generated by Django 5.2.4 on 2025-09-24 11:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_avatar_userprofile_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.JSONField(blank=True, default=list, help_text='List of options for MCQ'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Correct option for MCQ', max_length=200),
        ),
        migrations.CreateModel(
            name='DailyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('questions', models.JSONField(default=list)),
                ('answers', models.JSONField(default=list)),
                ('score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
