# Generated by Django 5.2.4 on 2025-09-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_question_category_remove_question_choices_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailymission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dailymission',
            name='date',
            field=models.DateField(),
        ),
    ]
