# Generated by Django 5.2.4 on 2025-09-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_quizquestion_remove_question_option_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='DifficultyLevel',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
